/*
 * GENERATED by tools/registry/gen.py from the registry/ text files. Do not edit:
 * edit the registry and run `make registry`.
 */

#include "apb.h"

/* Names are byte arrays so they stay ASCII everywhere, like all game text. */

static const char race_0[] = { 72, 117, 109, 97, 110, 0 };
static const char race_1[] = { 72, 111, 108, 108, 111, 119, 98, 111, 114, 110, 0 };
static const char race_2[] = { 71, 108, 97, 115, 115, 102, 111, 108, 107, 0 };
static const char race_3[] = { 82, 97, 100, 45, 68, 114, 121, 97, 100, 0 };
static const char race_4[] = { 67, 104, 114, 111, 110, 111, 109, 105, 116, 101, 0 };
static const char race_5[] = { 83, 97, 108, 118, 97, 103, 101, 100, 0 };
static const char race_6[] = { 77, 111, 116, 104, 45, 102, 111, 108, 107, 0 };
const char *const apb_race_names[APB_RACE_COUNT] = {
    race_0, race_1, race_2, race_3, race_4, race_5, race_6
};

const uint8_t apb_race_bonus[APB_RACE_COUNT] = {
    APB_FATE, APB_GRIT, APB_WITS, APB_PRESENCE, APB_GRACE, APB_MIGHT, APB_PRESENCE
};

static const char class_0[] = { 87, 97, 114, 100, 101, 110, 0 };
static const char class_1[] = { 82, 111, 103, 117, 101, 0 };
static const char class_2[] = { 84, 105, 110, 107, 101, 114, 0 };
static const char class_3[] = { 67, 104, 97, 110, 110, 101, 108, 101, 114, 0 };
static const char class_4[] = { 77, 101, 100, 105, 99, 0 };
const char *const apb_class_names[APB_CLASS_COUNT] = {
    class_0, class_1, class_2, class_3, class_4
};

const uint8_t apb_class_bonus[APB_CLASS_COUNT] = {
    APB_MIGHT, APB_GRACE, APB_WITS, APB_PRESENCE, APB_WITS
};

const uint8_t apb_class_tags[APB_CLASS_COUNT][2] = {
    { APB_SK_MELEE, APB_SK_ENDURANCE },  /* Warden */
    { APB_SK_STEALTH, APB_SK_RANGED },  /* Rogue */
    { APB_SK_TECH, APB_SK_LORE },  /* Tinker */
    { APB_SK_CHANNEL, APB_SK_INTUITION },  /* Channeler */
    { APB_SK_MEDICINE, APB_SK_SURVIVAL },  /* Medic */
};

static const char skill_0[] = { 77, 101, 108, 101, 101, 0 };
static const char skill_1[] = { 65, 116, 104, 108, 101, 116, 105, 99, 115, 0 };
static const char skill_2[] = { 82, 97, 110, 103, 101, 100, 0 };
static const char skill_3[] = { 83, 116, 101, 97, 108, 116, 104, 0 };
static const char skill_4[] = { 69, 110, 100, 117, 114, 97, 110, 99, 101, 0 };
static const char skill_5[] = { 83, 117, 114, 118, 105, 118, 97, 108, 0 };
static const char skill_6[] = { 84, 101, 99, 104, 0 };
static const char skill_7[] = { 77, 101, 100, 105, 99, 105, 110, 101, 0 };
static const char skill_8[] = { 76, 111, 114, 101, 0 };
static const char skill_9[] = { 80, 101, 114, 115, 117, 97, 100, 101, 0 };
static const char skill_10[] = { 67, 104, 97, 110, 110, 101, 108, 0 };
static const char skill_11[] = { 73, 110, 116, 117, 105, 116, 105, 111, 110, 0 };
const char *const apb_skill_names[APB_SKILL_COUNT] = {
    skill_0, skill_1, skill_2, skill_3, skill_4, skill_5, skill_6, skill_7, skill_8, skill_9, skill_10, skill_11
};

const uint8_t apb_skill_stat[APB_SKILL_COUNT] = {
    APB_MIGHT, APB_MIGHT, APB_GRACE, APB_GRACE, APB_GRIT, APB_GRIT, APB_WITS, APB_WITS, APB_WITS, APB_PRESENCE, APB_PRESENCE, APB_FATE
};

static const char item_none[] = { 0 };
static const char item_1[] = { 80, 117, 108, 115, 101, 32, 114, 105, 102, 108, 101, 0 };
static const char item_2[] = { 66, 97, 108, 108, 105, 115, 116, 105, 99, 32, 119, 101, 97, 118, 101, 0 };
static const char item_3[] = { 77, 101, 100, 45, 115, 99, 97, 110, 110, 101, 114, 0 };
static const char item_4[] = { 72, 111, 118, 101, 114, 45, 98, 105, 107, 101, 0 };
static const char item_5[] = { 82, 117, 115, 116, 101, 100, 32, 115, 97, 98, 114, 101, 0 };
static const char item_6[] = { 77, 69, 82, 73, 68, 73, 65, 78, 39, 115, 32, 99, 111, 114, 101, 0 };
static const char item_7[] = { 66, 108, 97, 110, 107, 32, 116, 105, 99, 107, 101, 116, 32, 115, 116, 117, 98, 0 };

/* Indexed by item id; ids with no item are all zeros. */
const apb_item_def apb_items[APB_ITEM_COUNT] = {
    { 0, 0, 0, 0, 0 },
    { APB_ARCH_RANGED, 4, APB_DMG_ENERGY, 8, 0 },  /* PULSE_RIFLE */
    { APB_ARCH_ARMOR, 3, APB_DMG_KINETIC, 8, 0 },  /* BALLISTIC_WEAVE */
    { APB_ARCH_TOOL, 2, APB_DMG_MIND, 7, 0 },  /* MED_SCANNER */
    { APB_ARCH_VEHICLE, 3, APB_DMG_KINETIC, 8, 0 },  /* HOVER_BIKE */
    { APB_ARCH_MELEE, 1, APB_DMG_KINETIC, 3, 0 },  /* RUSTED_SABRE */
    { APB_ARCH_FOCUS, 2, APB_DMG_MIND, 8, 0 },  /* MERIDIAN_CORE */
    { APB_ARCH_FOCUS, 1, APB_DMG_MIND, 5, 5 },  /* TICKET_STUB */
};

const char *const apb_item_names[APB_ITEM_COUNT] = {
    item_none, item_1, item_2, item_3, item_4, item_5, item_6, item_7
};

/* Canon default state of each Echo, indexed by id. */
const uint8_t apb_echo_defaults[APB_ECHO_COUNT] = {
    0, 2, 2, 1, 2, 2, 1, 2, 1, 2
};
