/*
 * GENERATED by tools/registry/gen.py from the registry/ text files. Do not edit:
 * edit the registry and run `make registry`.
 */

#ifndef APB_REGISTRY_H
#define APB_REGISTRY_H

/* Races */
enum {
    APB_HUMAN = 0,
    APB_HOLLOWBORN = 1,
    APB_GLASSFOLK = 2,
    APB_RAD_DRYAD = 3,
    APB_CHRONOMITE = 4,
    APB_SALVAGED = 5,
    APB_MOTH_FOLK = 6,
    APB_RACE_COUNT
};

/* Classes */
enum {
    APB_WARDEN = 0,
    APB_ROGUE = 1,
    APB_TINKER = 2,
    APB_CHANNELER = 3,
    APB_MEDIC = 4,
    APB_CLASS_COUNT
};

/* Skills */
enum {
    APB_SK_MELEE = 0,
    APB_SK_ATHLETICS = 1,
    APB_SK_RANGED = 2,
    APB_SK_STEALTH = 3,
    APB_SK_ENDURANCE = 4,
    APB_SK_SURVIVAL = 5,
    APB_SK_TECH = 6,
    APB_SK_MEDICINE = 7,
    APB_SK_LORE = 8,
    APB_SK_PERSUADE = 9,
    APB_SK_CHANNEL = 10,
    APB_SK_INTUITION = 11,
    APB_SKILL_COUNT
};

/* Items: 1..1023, 0 = empty. */
#define APB_ITEM_NONE 0
#define APB_ITEM_PULSE_RIFLE 1  /* ranged t4 energy TL8 ML0 */
#define APB_ITEM_BALLISTIC_WEAVE 2  /* armor t3 kinetic TL8 ML0 */
#define APB_ITEM_MED_SCANNER 3  /* tool t2 mind TL7 ML0 */
#define APB_ITEM_HOVER_BIKE 4  /* vehicle t3 kinetic TL8 ML0 */
#define APB_ITEM_RUSTED_SABRE 5  /* melee t1 kinetic TL3 ML0 */
#define APB_ITEM_MERIDIAN_CORE 6  /* focus t2 mind TL8 ML0 */
#define APB_ITEM_TICKET_STUB 7  /* focus t1 mind TL5 ML5 */
#define APB_ITEM_PORTERS_HOOK 8  /* melee t1 kinetic TL3 ML0 */
#define APB_ITEM_COUNT 9  /* highest id + 1 */

/* Echoes: 1..1023. States are 1..3; 0 means unset. */
#define APB_ECHO_MERIDIAN 1  /* Departure 01 */
#define   APB_MERIDIAN_FREED 1
#define   APB_MERIDIAN_WIPED 2  /* canon default */
#define   APB_MERIDIAN_CARRIED 3
#define APB_ECHO_KEPLER_CREW 2  /* Departure 01 */
#define   APB_KEPLER_CREW_SAVED 1
#define   APB_KEPLER_CREW_LOST 2  /* canon default */
#define APB_ECHO_SEED_VAULT 3  /* Departure 01 */
#define   APB_SEED_VAULT_DELIVERED 1  /* canon default */
#define   APB_SEED_VAULT_KEPT 2
#define   APB_SEED_VAULT_DESTROYED 3
#define APB_ECHO_WOLF_PUP 4  /* Departure 02 */
#define   APB_WOLF_PUP_SAVED 1
#define   APB_WOLF_PUP_LEFT 2  /* canon default */
#define   APB_WOLF_PUP_SWORN 3
#define APB_ECHO_JACE_CUTTER 5  /* Departure 02 */
#define   APB_JACE_CUTTER_SPARED 1
#define   APB_JACE_CUTTER_KILLED 2  /* canon default */
#define   APB_JACE_CUTTER_RECRUITED 3
#define APB_ECHO_OREN_VEY 6  /* Departure 02 */
#define   APB_OREN_VEY_BOARDED 1  /* canon default */
#define   APB_OREN_VEY_STAYED 2
#define APB_ECHO_YSOLDE 7  /* Departure 03 */
#define   APB_YSOLDE_BEFRIENDED 1
#define   APB_YSOLDE_EXPOSED 2  /* canon default */
#define   APB_YSOLDE_DESTROYED 3
#define APB_ECHO_LANTERN_COURT 8  /* Departure 03 */
#define   APB_LANTERN_COURT_WELCOME 1  /* canon default */
#define   APB_LANTERN_COURT_BANISHED 2
#define APB_ECHO_YSOLDE_LEDGER 9  /* Departure 03 */
#define   APB_YSOLDE_LEDGER_READ 1
#define   APB_YSOLDE_LEDGER_BURNED 2  /* canon default */
#define APB_ECHO_COUNT 10  /* highest id + 1 */

#endif
