"""Generate the C registry from registry/*.txt.

    python3 tools/registry/gen.py [output directory]

Writes apb_registry.h (ids and counts) and registry.c (name, bonus, item and
Echo tables). With no argument, writes them into core/include and core/src.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from registry import ARCHETYPES, DAMAGE, STATS, by_id, load  # noqa: E402

REPO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")

BANNER = """/*
 * GENERATED by tools/registry/gen.py from the registry/ text files. Do not edit:
 * edit the registry and run `make registry`.
 */
"""


def stat_c(i):
    return "APB_" + STATS[i]


def name_bytes(text):
    # Byte arrays rather than string literals, so names stay ASCII on every
    # platform: cc65 turns string literals into PETSCII on the C64.
    return "{ " + ", ".join(str(ord(c)) for c in text) + ", 0 }"


def header(reg):
    out = [BANNER, "#ifndef APB_REGISTRY_H", "#define APB_REGISTRY_H", ""]

    def enum(title, prefix, table, count):
        out.append(f"/* {title} */")
        out.append("enum {")
        for e in sorted(table.values(), key=lambda e: e["id"]):
            out.append(f"    {prefix}{e['name']} = {e['id']},")
        out.append(f"    {count}")
        out.append("};")
        out.append("")

    enum("Races", "APB_", reg["races"], "APB_RACE_COUNT")
    enum("Classes", "APB_", reg["classes"], "APB_CLASS_COUNT")
    enum("Skills", "APB_SK_", reg["skills"], "APB_SKILL_COUNT")

    items = sorted(reg["items"].values(), key=lambda e: e["id"])
    out.append("/* Items: 1..1023, 0 = empty. */")
    out.append("#define APB_ITEM_NONE 0")
    for e in items:
        note = (f"{ARCHETYPES[e['archetype']]} t{e['tier']} {DAMAGE[e['damage']]} "
                f"TL{e['tl']} ML{e['ml']}")
        out.append(f"#define APB_ITEM_{e['name']} {e['id']}  /* {note} */")
    out.append(f"#define APB_ITEM_COUNT {items[-1]['id'] + 1 if items else 1}"
               "  /* highest id + 1 */")
    out.append("")

    echoes = sorted(reg["echoes"].values(), key=lambda e: e["id"])
    out.append("/* Echoes: 1..1023. States are 1..3; 0 means unset. */")
    for e in echoes:
        out.append(f"#define APB_ECHO_{e['name']} {e['id']}  /* Departure {e['departure']} */")
        for i, s in enumerate(e["states"], 1):
            mark = "  /* canon default */" if i == e["default"] else ""
            out.append(f"#define   APB_{e['name']}_{s} {i}{mark}")
    out.append(f"#define APB_ECHO_COUNT {echoes[-1]['id'] + 1 if echoes else 1}"
               "  /* highest id + 1 */")
    out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


def source(reg):
    out = [BANNER, '#include "apb.h"', ""]
    out.append("/* Names are byte arrays so they stay ASCII everywhere, like all game text. */")
    out.append("")

    def names(kind, table, count):
        rows = sorted(table.values(), key=lambda e: e["id"])
        for e in rows:
            out.append(f"static const char {kind}_{e['id']}[] = {name_bytes(e['display'])};")
        out.append(f"const char *const apb_{kind}_names[{count}] = {{")
        out.append("    " + ", ".join(f"{kind}_{e['id']}" for e in rows))
        out.append("};")
        out.append("")
        return rows

    rows = names("race", reg["races"], "APB_RACE_COUNT")
    out.append("const uint8_t apb_race_bonus[APB_RACE_COUNT] = {")
    out.append("    " + ", ".join(stat_c(e["bonus"]) for e in rows))
    out.append("};")
    out.append("")

    rows = names("class", reg["classes"], "APB_CLASS_COUNT")
    out.append("const uint8_t apb_class_bonus[APB_CLASS_COUNT] = {")
    out.append("    " + ", ".join(stat_c(e["bonus"]) for e in rows))
    out.append("};")
    out.append("")
    skills = by_id(reg["skills"])
    out.append("const uint8_t apb_class_tags[APB_CLASS_COUNT][2] = {")
    for e in rows:
        a, b = (f"APB_SK_{skills[t]['name']}" for t in e["tags"])
        out.append(f"    {{ {a}, {b} }},  /* {e['display']} */")
    out.append("};")
    out.append("")

    rows = names("skill", reg["skills"], "APB_SKILL_COUNT")
    out.append("const uint8_t apb_skill_stat[APB_SKILL_COUNT] = {")
    out.append("    " + ", ".join(stat_c(e["stat"]) for e in rows))
    out.append("};")
    out.append("")

    items = by_id(reg["items"])
    out.append("static const char item_none[] = { 0 };")
    for i, e in sorted(items.items()):
        out.append(f"static const char item_{i}[] = {name_bytes(e['display'])};")
    out.append("")
    out.append("/* Indexed by item id; ids with no item are all zeros. */")
    out.append("const apb_item_def apb_items[APB_ITEM_COUNT] = {")
    top = max(items) if items else 0
    for i in range(top + 1):
        e = items.get(i)
        if e is None:
            out.append("    { 0, 0, 0, 0, 0 },")
        else:
            out.append(f"    {{ APB_ARCH_{ARCHETYPES[e['archetype']].upper()}, {e['tier']}, "
                       f"APB_DMG_{DAMAGE[e['damage']].upper()}, {e['tl']}, {e['ml']} }},"
                       f"  /* {e['name']} */")
    out.append("};")
    out.append("")
    out.append("const char *const apb_item_names[APB_ITEM_COUNT] = {")
    out.append("    " + ", ".join(f"item_{i}" if i in items else "item_none"
                                  for i in range(top + 1)))
    out.append("};")
    out.append("")

    echoes = by_id(reg["echoes"])
    top = max(echoes) if echoes else 0
    out.append("/* Canon default state of each Echo, indexed by id. */")
    out.append("const uint8_t apb_echo_defaults[APB_ECHO_COUNT] = {")
    out.append("    " + ", ".join(str(echoes[i]["default"]) if i in echoes else "0"
                                  for i in range(top + 1)))
    out.append("};")
    out.append("")
    out.append("/* The Departure that plants each Echo, indexed by id: a Rewind of it replaces them. */")
    out.append("const uint16_t apb_echo_departures[APB_ECHO_COUNT] = {")
    out.append("    " + ", ".join(str(echoes[i]["departure_id"]) if i in echoes else "0xFFFF"
                                  for i in range(top + 1)))
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    reg = load()
    if len(sys.argv) > 1:
        inc = src = sys.argv[1]
        os.makedirs(inc, exist_ok=True)
    else:
        inc = os.path.join(REPO, "core", "include")
        src = os.path.join(REPO, "core", "src")
    with open(os.path.join(inc, "apb_registry.h"), "w", newline="\n") as f:
        f.write(header(reg))
    with open(os.path.join(src, "registry.c"), "w", newline="\n") as f:
        f.write(source(reg))


if __name__ == "__main__":
    main()
