"""The registry's names for the cartridge (docs/cartridge.md), as ca65 source.

    python3 tools/registry/registry_asm.py OUT.s

The races', classes', skills' and items' display names, ASCII, each ending in 0, with
tables of where they are (race_lo/race_hi, class_lo/class_hi, skill_lo/skill_hi,
item_lo/item_hi), indexed by id, and their counts; each skill's stat (skill_stat, 0-5),
each item's tier (item_tier: 0 for an id with no item), and each Echo's default state and
Departure (echo_default, echo_dep_lo/echo_dep_hi). From registry/*.txt through
tools/registry/registry.py, the one source of truth; generated at build time, never
edited.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import registry  # noqa: E402


def table(kind, entries):
    by_id = {e["id"]: e["display"] for e in entries.values()}
    ids = range(max(by_id) + 1)
    out = [f"{kind}_lo:"] + [f"        .byte <{kind}_{i}" for i in ids]
    out += [f"{kind}_hi:"] + [f"        .byte >{kind}_{i}" for i in ids]
    for i in ids:
        text = by_id.get(i, "?").replace('"', "'")
        out.append(f'{kind}_{i}: .byte "{text}", 0')
    return out, len(ids)


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    reg = registry.load()
    races, n_races = table("race", reg["races"])
    classes, n_classes = table("class", reg["classes"])
    skills, n_skills = table("skill", reg["skills"])
    items, n_items = table("item", reg["items"])
    stats = {e["id"]: e["stat"] for e in reg["skills"].values()}
    tiers = {e["id"]: e["tier"] for e in reg["items"].values()}
    lines = ["; Generated by tools/registry/registry_asm.py from registry/*.txt: don't edit.",
             "", "        .export race_lo, race_hi, class_lo, class_hi, skill_lo, skill_hi",
             "        .export item_lo, item_hi, skill_stat, item_tier",
             "        .export echo_default, echo_dep_lo, echo_dep_hi",
             "        .exportzp RACE_COUNT, CLASS_COUNT, SKILL_COUNT, ITEM_COUNT, ECHO_COUNT"
             "     ; (8-bit numbers)",
             "", f"RACE_COUNT = {n_races}", f"CLASS_COUNT = {n_classes}",
             f"SKILL_COUNT = {n_skills}", f"ITEM_COUNT = {n_items}",
             f"ECHO_COUNT = {max([e['id'] for e in reg['echoes'].values()] or [0]) + 1}", "",
             '        .segment "RESIDENT"', ""] + races + [""] + classes + [""] + skills
    lines += ["", "skill_stat:"] + [f"        .byte {stats[i]}" for i in range(n_skills)]
    lines += [""] + items
    lines += ["", "item_tier:"] + [f"        .byte {tiers.get(i, 0)}" for i in range(n_items)]
    echoes = {e["id"]: e for e in reg["echoes"].values()}
    n_echoes = max(echoes) + 1 if echoes else 1
    lines += ["", "; Each Echo's default state (0: no Echo), and the Departure it belongs to.",
              "echo_default:"] + [f"        .byte {echoes[i]['default'] if i in echoes else 0}"
                                  for i in range(n_echoes)]
    lines += ["echo_dep_lo:"] + [f"        .byte <{echoes[i]['departure_id'] if i in echoes else 0}"
                                 for i in range(n_echoes)]
    lines += ["echo_dep_hi:"] + [f"        .byte >{echoes[i]['departure_id'] if i in echoes else 0}"
                                 for i in range(n_echoes)]
    with open(argv[1], "w") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
