"""The registry's names for the cartridge (docs/cartridge.md), as ca65 source.

    python3 tools/registry/registry_asm.py OUT.s

The races' and classes' display names, ASCII, each ending in 0, with tables of where
they are: race_lo/race_hi and class_lo/class_hi, indexed by id, and RACE_COUNT and
CLASS_COUNT. From registry/*.txt through tools/registry/registry.py, the one source of
truth; generated at build time, never edited.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import registry  # noqa: E402


def table(kind, entries):
    by_id = {e["id"]: e["display"] for e in entries.values()}
    ids = range(max(by_id) + 1)
    out = [f"{kind}_lo:"] + [f"        .byte <{kind}_{i}" for i in ids]
    out += [f"{kind}_hi:"] + [f"        .byte >{kind}_{i}" for i in ids]
    for i in ids:
        text = by_id.get(i, "?").replace('"', "'")
        out.append(f'{kind}_{i}: .byte "{text}", 0')
    return out, len(ids)


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    reg = registry.load()
    races, n_races = table("race", reg["races"])
    classes, n_classes = table("class", reg["classes"])
    lines = ["; Generated by tools/registry/registry_asm.py from registry/*.txt: don't edit.",
             "", "        .export race_lo, race_hi, class_lo, class_hi",
             "        .exportzp RACE_COUNT, CLASS_COUNT     ; (8-bit numbers)",
             "", f"RACE_COUNT = {n_races}", f"CLASS_COUNT = {n_classes}", "",
             '        .segment "RESIDENT"', ""] + races + [""] + classes
    with open(argv[1], "w") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
